import type { Category, Recipe } from "./types";

export const categories: Category[] = [
  { slug: "sopas-y-cremas", nombre: "Sopas y Cremas", descripcion: "Sopas, cremas y potajes adaptados a tu Mambo.", icono: "🥣" },
  { slug: "arroces", nombre: "Arroces", descripcion: "Paellas, risottos y arroces melosos.", icono: "🍚" },
  { slug: "carnes", nombre: "Carnes", descripcion: "Estofados, asados y carnes al punto.", icono: "🥩" },
  { slug: "pescados", nombre: "Pescados", descripcion: "Pescados y mariscos con vapor y más.", icono: "🐟" },
  { slug: "postres", nombre: "Postres", descripcion: "Bizcochos, helados, natillas y dulces.", icono: "🍰" },
  { slug: "salsas", nombre: "Salsas", descripcion: "Salsas, pestos y aliños caseros.", icono: "🫙" },
  { slug: "panes-masas", nombre: "Panes y Masas", descripcion: "Pan casero, pizza, bollería.", icono: "🍞" },
  { slug: "verduras", nombre: "Verduras", descripcion: "Guarniciones, salteados y verduras al vapor.", icono: "🥦" },
  { slug: "bebidas", nombre: "Bebidas", descripcion: "Zumos, batidos, smoothies y helados.", icono: "🥤" },
  { slug: "legumbres", nombre: "Legumbres", descripcion: "Lentejas, garbanzos, judías y más.", icono: "🫘" },
];

export const seedRecipes: Recipe[] = [
  {
    id: "1",
    slug: "sofrito-base-mambo",
    titulo: "Sofrito Base en Mambo",
    descripcion: "El sofrito perfecto para paellas, arroces y guisos. Adaptado para la inducción de la Mambo Cooking Total Gourmet con mayor temperatura para un dorado perfecto.",
    imagen: "/images/recipes/sofrito-base-mambo.jpg",
    categoria: "salsas",
    tiempo_total_min: 15,
    comensales: 4,
    dificultad: "Fácil",
    ingredientes: [
      "50 g de aceite de oliva virgen extra",
      "200 g de cebolla troceada",
      "1 diente de ajo",
      "200 g de tomate maduro rallado",
      "1 cucharadita de sal",
      "1 pizca de pimentón dulce",
    ],
    pasos_mambo: [
      { paso_numero: 1, instruccion: "Colocar la cebolla y el ajo en la jarra. Triturar.", accesorio: "Cuchillas", velocidad: 5, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: 5 },
      { paso_numero: 2, instruccion: "Añadir el aceite y programar. La inducción Mambo permite dorar mejor a 135 ºC.", accesorio: "Cuchillas", velocidad: 1, temperatura_c: 135, potencia_calorifica: 7, tiempo_minutos: 5 },
      { paso_numero: 3, instruccion: "Incorporar el tomate rallado, la sal y el pimentón. Cocinar hasta que oscurezca.", accesorio: "Cuchillas", velocidad: 1, temperatura_c: 130, potencia_calorifica: 6, tiempo_minutos: 5 },
    ],
    creado_en: "2026-08-11",
    destacada: true,
  },
  {
    id: "2",
    slug: "arroz-con-leche-mambo",
    titulo: "Arroz con Leche Tradicional",
    descripcion: "El clásico postre asturiano, cremoso y con canela. Perfecto en la Mambo gracias a la potencia calórica constante que evita que se pegue.",
    imagen: "/images/recipes/arroz-con-leche-mambo.jpg",
    categoria: "postres",
    tiempo_total_min: 45,
    comensales: 6,
    dificultad: "Fácil",
    ingredientes: [
      "200 g de arroz",
      "1 litro de leche entera",
      "150 g de azúcar",
      "1 rama de canela",
      "1 pizca de sal",
      "Canela molida para espolvorear",
      "Mantequilla (opcional, para brasear)",
    ],
    pasos_mambo: [
      { paso_numero: 1, instruccion: "Colocar la leche, el arroz, la rama de canela y la sal en la jarra. Programar a fuego lento.", accesorio: "Cuchillas", velocidad: 1, temperatura_c: 95, potencia_calorifica: 4, tiempo_minutos: 25 },
      { paso_numero: 2, instruccion: "Retirar la rama de canela. Añadir el azúcar y triturar ligeramente para lograr cremosidad.", accesorio: "Cuchillas", velocidad: 3, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: 1 },
      { paso_numero: 3, instruccion: "Programar de nuevo para que espese, removiendo con la Pala MamboMix.", accesorio: "Pala MamboMix", velocidad: 1, temperatura_c: 90, potencia_calorifica: 4, tiempo_minutos: 5 },
      { paso_numero: 4, instruccion: "Servir en cazuelitas y espolvorear canela al gusto. Opcional: gratinar con un soplete.", accesorio: "Ninguno", velocidad: 0, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: null },
    ],
    creado_en: "2026-08-11",
    destacada: true,
  },
  {
    id: "3",
    slug: "pure-de-patatas-mambo",
    titulo: "Puré de Patatas Cremoso",
    descripcion: "El puré más esponjoso y cremoso, con el punto justo de mantequilla. La Mambo cocina las patatas al vapor en menos tiempo.",
    imagen: "/images/recipes/pure-de-patatas-mambo.jpg",
    categoria: "verduras",
    tiempo_total_min: 30,
    comensales: 4,
    dificultad: "Fácil",
    ingredientes: [
      "800 g de patatas peladas y troceadas",
      "200 g de leche entera",
      "50 g de mantequilla",
      "1 cucharadita de sal",
      "1 pizca de nuez moscada",
    ],
    pasos_mambo: [
      { paso_numero: 1, instruccion: "Colocar las patatas en el cestillo. Añadir agua hasta la marca inferior de la jarra. Cocinar al vapor.", accesorio: "Ninguno", velocidad: 0, temperatura_c: 120, potencia_calorifica: 9, tiempo_minutos: 20 },
      { paso_numero: 2, instruccion: "Verter el agua, colocar las patatas en la jarra. Añadir mantequilla, leche, sal y nuez moscada.", accesorio: "Cuchillas", velocidad: 4, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: 1 },
      { paso_numero: 3, instruccion: "Si queda muy espeso, añadir un poco más de leche y mezclar de nuevo.", accesorio: "Cuchillas", velocidad: 3, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: 1 },
    ],
    creado_en: "2026-08-11",
  },
  {
    id: "4",
    slug: "cocido-madrileno-mambo",
    titulo: "Cocido Madrileño Completo",
    descripcion: "El plato más castizo de Madrid, adaptado a la Mambo Cooking Total Gourmet. Con su sopa, garbanzos y vuelta y vuelta.",
    imagen: "/images/recipes/cocido-madrileno-mambo.jpg",
    categoria: "legumbres",
    tiempo_total_min: 90,
    comensales: 6,
    dificultad: "Media",
    ingredientes: [
      "300 g de garbanzos remojados",
      "200 g de morcillo de ternera",
      "100 g de tocino ibérico",
      "1 hueso de jamón",
      "2 patatas medianas",
      "1 zanahoria",
      "1 puerro",
      "1/2 repollo",
      "200 g de fideos",
      "Sal al gusto",
    ],
    pasos_mambo: [
      { paso_numero: 1, instruccion: "Colocar los garbanzos, el morcillo, el tocino y el hueso de jamón en la jarra. Cubrir con agua. Programar.", accesorio: "Cuchillas", velocidad: 0, temperatura_c: 120, potencia_calorifica: 9, tiempo_minutos: 45 },
      { paso_numero: 2, instruccion: "Añadir las patatas, la zanahoria y el puerro troceados. Programar.", accesorio: "Cuchillas", velocidad: 0, temperatura_c: 120, potencia_calorifica: 7, tiempo_minutos: 20 },
      { paso_numero: 3, instruccion: "Retirar el repollo, trocearlo y añadirlo. Programar de nuevo.", accesorio: "Cuchillas", velocidad: 0, temperatura_c: 120, potencia_calorifica: 6, tiempo_minutos: 10 },
      { paso_numero: 4, instruccion: "Colar la sopa y reservar los garbanzos y la carne. En la sopa, cocinar los fideos.", accesorio: "Cuchillas", velocidad: 1, temperatura_c: 100, potencia_calorifica: 9, tiempo_minutos: 8 },
    ],
    creado_en: "2026-08-11",
    destacada: true,
  },
  {
    id: "5",
    slug: "bizcocho-de-yogur-mambo",
    titulo: "Bizcocho de Yogur Esponjoso",
    descripcion: "El bizcocho más fácil y esponjoso. Con la Mambo preparas la masa en 1 minuto y el horno hace el resto.",
    imagen: "/images/recipes/bizcocho-de-yogur-mambo.jpg",
    categoria: "postres",
    tiempo_total_min: 50,
    comensales: 8,
    dificultad: "Fácil",
    ingredientes: [
      "1 yogur natural (usar el vaso como medida)",
      "3 vasos de harina",
      "2 vasos de azúcar",
      "3 huevos",
      "1/2 vaso de aceite de girasol",
      "1 sobre de levadura química",
      "Ralladura de limón",
    ],
    pasos_mambo: [
      { paso_numero: 1, instruccion: "Colocar los huevos y el azúcar en la jarra. Montar a velocidad alta.", accesorio: "Cuchillas", velocidad: 4, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: 2 },
      { paso_numero: 2, instruccion: "Añadir el yogur, el aceite y la ralladura de limón. Mezclar.", accesorio: "Cuchillas", velocidad: 3, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: 1 },
      { paso_numero: 3, instruccion: "Incorporar la harina y la levadura. Mezclar en pulsaciones para evitar grumos.", accesorio: "Cuchillas", velocidad: 3, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: 1 },
      { paso_numero: 4, instruccion: "Verter en un molde engrasado y hornear a 180 ºC durante 35 minutos.", accesorio: "Ninguno", velocidad: 0, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: 35 },
    ],
    creado_en: "2026-08-11",
  },
  {
    id: "6",
    slug: "guiso-de-carne-con-garbanzos-mambo",
    titulo: "Guiso de Carne Picada con Garbanzos",
    descripcion: "Un guiso contundente y sabroso, perfecto para días de frío. La inducción Mambo consigue un sofrito espectacular.",
    imagen: "/images/recipes/guiso-de-carne-con-garbanzos-mambo.jpg",
    categoria: "carnes",
    tiempo_total_min: 45,
    comensales: 4,
    dificultad: "Media",
    ingredientes: [
      "400 g de carne picada mixta",
      "250 g de garbanzos cocidos",
      "1 cebolla",
      "2 dientes de ajo",
      "200 g de tomate triturado",
      "1 cucharadita de pimentón dulce",
      "1/2 cucharadita de comino",
      "200 ml de caldo de carne",
      "Aceite de oliva, sal y pimienta",
    ],
    pasos_mambo: [
      { paso_numero: 1, instruccion: "Picar la cebolla y el ajo. Programar con aceite a temperatura alta para dorar (aprovechamiento de inducción).", accesorio: "Cuchillas", velocidad: 1, temperatura_c: 140, potencia_calorifica: 7, tiempo_minutos: 5 },
      { paso_numero: 2, instruccion: "Añadir la carne picada y desmenuzar con la Pala MamboMix.", accesorio: "Pala MamboMix", velocidad: 2, temperatura_c: 130, potencia_calorifica: 7, tiempo_minutos: 8 },
      { paso_numero: 3, instruccion: "Incorporar el tomate, el pimentón y el comino. Cocinar.", accesorio: "Pala MamboMix", velocidad: 1, temperatura_c: 120, potencia_calorifica: 6, tiempo_minutos: 5 },
      { paso_numero: 4, instruccion: "Añadir los garbanzos y el caldo. Guisar a fuego medio.", accesorio: "Pala MamboMix", velocidad: 1, temperatura_c: 100, potencia_calorifica: 5, tiempo_minutos: 20 },
    ],
    creado_en: "2026-08-11",
    destacada: true,
  },
  {
    id: "7",
    slug: "merluza-al-vapor-mambo",
    titulo: "Merluza al Vapor con Verduras",
    descripcion: "Punto perfecto de cocción al vapor con la Mambo. El cestillo y la potencia 9 garantizan una merluza jugosa.",
    imagen: "/images/recipes/merluza-al-vapor-mambo.jpg",
    categoria: "pescados",
    tiempo_total_min: 25,
    comensales: 4,
    dificultad: "Fácil",
    ingredientes: [
      "4 lomos de merluza fresca",
      "200 g de judías verdes",
      "1 zanahoria en bastones",
      "1 limón",
      "Aceite de oliva virgen extra",
      "Sal y pimienta",
      "Perejil fresco",
    ],
    pasos_mambo: [
      { paso_numero: 1, instruccion: "Colocar las judías verdes y la zanahoria en el cestillo. Añadir agua a la jarra.", accesorio: "Ninguno", velocidad: 0, temperatura_c: 120, potencia_calorifica: 9, tiempo_minutos: 10 },
      { paso_numero: 2, instruccion: "Colocar los lomos de merluza sazonados sobre las verduras. Programar vapor.", accesorio: "Ninguno", velocidad: 0, temperatura_c: 120, potencia_calorifica: 9, tiempo_minutos: 12 },
      { paso_numero: 3, instruccion: "Servir con un chorro de aceite, limón y perejil picado.", accesorio: "Ninguno", velocidad: 0, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: null },
    ],
    creado_en: "2026-08-11",
  },
  {
    id: "8",
    slug: "sopa-de-ajo-mambo",
    titulo: "Sopa de Ajo Tradicional",
    descripcion: "Reconfortante y llena de sabor. El calentamiento rápido por inducción de la Mambo la hace en un suspiro.",
    imagen: "/images/recipes/sopa-de-ajo-mambo.jpg",
    categoria: "sopas-y-cremas",
    tiempo_total_min: 20,
    comensales: 4,
    dificultad: "Fácil",
    ingredientes: [
      "6 dientes de ajo",
      "100 g de pan duro",
      "1 litro de caldo de pollo",
      "1 cucharadita de pimentón de la Vera",
      "4 huevos",
      "100 ml de aceite de oliva virgen extra",
      "Sal",
    ],
    pasos_mambo: [
      { paso_numero: 1, instruccion: "Colocar los ajos en la jarra y laminar.", accesorio: "Cuchillas", velocidad: 4, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: 3 },
      { paso_numero: 2, instruccion: "Añadir aceite y sofreír a temperatura alta (inducción Mambo).", accesorio: "Cuchillas", velocidad: 1, temperatura_c: 130, potencia_calorifica: 7, tiempo_minutos: 5 },
      { paso_numero: 3, instruccion: "Incorporar el pan, el pimentón y el caldo. Hervir.", accesorio: "Cuchillas", velocidad: 0, temperatura_c: 100, potencia_calorifica: 9, tiempo_minutos: 8 },
      { paso_numero: 4, instruccion: "Hacer huevos escalfados directamente en el caldo o en un bol aparte al baño María.", accesorio: "Ninguno", velocidad: 0, temperatura_c: 90, potencia_calorifica: 5, tiempo_minutos: 4 },
    ],
    creado_en: "2026-08-11",
  },
  {
    id: "9",
    slug: "pesto-casero-mambo",
    titulo: "Pesto Genovés Casero",
    descripcion: "En un minuto tienes el pesto más fresco y aromático. Las cuchillas de la Mambo lo trituran al punto perfecto.",
    imagen: "/images/recipes/pesto-casero-mambo.jpg",
    categoria: "salsas",
    tiempo_total_min: 5,
    comensales: 4,
    dificultad: "Fácil",
    ingredientes: [
      "50 g de albahaca fresca",
      "30 g de piñones",
      "30 g de parmesano rallado",
      "1 diente de ajo",
      "100 ml de aceite de oliva virgen extra",
      "Sal",
    ],
    pasos_mambo: [
      { paso_numero: 1, instruccion: "Colocar la albahaca, los piñones, el ajo y el queso en la jarra. Triturar.", accesorio: "Cuchillas", velocidad: 6, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: 1 },
      { paso_numero: 2, instruccion: "Añadir el aceite en chorro fino mientras tritura a velocidad media.", accesorio: "Cuchillas", velocidad: 4, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: 1 },
      { paso_numero: 3, instruccion: "Rectificar de sal y guardar en un tarro. Se conserva 1 semana en la nevera.", accesorio: "Ninguno", velocidad: 0, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: null },
    ],
    creado_en: "2026-08-11",
  },
  {
    id: "10",
    slug: "lentejas-mambo",
    titulo: "Lentejas Estofadas",
    descripcion: "Lentejas con verduras y chorizo, guisadas a la perfección en la Mambo. La Pala MamboMix evita que se peguen.",
    imagen: "/images/recipes/lentejas-mambo.jpg",
    categoria: "legumbres",
    tiempo_total_min: 50,
    comensales: 6,
    dificultad: "Media",
    ingredientes: [
      "400 g de lentejas pardinas",
      "1 chorizo",
      "1 patata grande",
      "1 zanahoria",
      "1 puerro",
      "1/2 cebolla",
      "2 dientes de ajo",
      "1 hoja de laurel",
      "1 cucharadita de pimentón dulce",
      "1 cucharadita de comino",
      "1 litro de agua",
      "Sal y aceite",
    ],
    pasos_mambo: [
      { paso_numero: 1, instruccion: "Picar la cebolla, el ajo, el puerro y la zanahoria. Sofreír con aceite y chorizo.", accesorio: "Pala MamboMix", velocidad: 1, temperatura_c: 135, potencia_calorifica: 7, tiempo_minutos: 8 },
      { paso_numero: 2, instruccion: "Añadir el pimentón, las lentejas lavadas, la patata, el laurel y el agua. Programar.", accesorio: "Pala MamboMix", velocidad: 1, temperatura_c: 100, potencia_calorifica: 5, tiempo_minutos: 35 },
      { paso_numero: 3, instruccion: "Comprobar que las lentejas están tiernas. Si es necesario, añadir más agua y programar unos minutos más.", accesorio: "Pala MamboMix", velocidad: 1, temperatura_c: 100, potencia_calorifica: 5, tiempo_minutos: 5 },
    ],
    creado_en: "2026-08-11",
    destacada: true,
  },
  {
    id: "11",
    slug: "smoothie-de-frutas-rojas-mambo",
    titulo: "Smoothie de Frutas Rojas",
    descripcion: "Refrescante, saludable y listo en 1 minuto. Las cuchillas de la Mambo lo dejan perfectamente cremoso.",
    imagen: "/images/recipes/smoothie-de-frutas-rojas-mambo.jpg",
    categoria: "bebidas",
    tiempo_total_min: 3,
    comensales: 2,
    dificultad: "Fácil",
    ingredientes: [
      "200 g de frutas rojas congeladas (fresas, arándanos, frambuesas)",
      "1 plátano maduro",
      "200 ml de leche de almendras",
      "1 cucharada de miel",
      "4-5 cubos de hielo",
    ],
    pasos_mambo: [
      { paso_numero: 1, instruccion: "Colocar todas las frutas, la leche de almendras y la miel en la jarra.", accesorio: "Cuchillas", velocidad: 8, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: 1 },
      { paso_numero: 2, instruccion: "Añadir los cubos de hielo y triturar hasta obtener una textura homogénea.", accesorio: "Cuchillas", velocidad: "Turbo", temperatura_c: null, potencia_calorifica: null, tiempo_minutos: 1 },
    ],
    creado_en: "2026-08-11",
  },
  {
    id: "12",
    slug: "pan-de-molde-mambo",
    titulo: "Pan de Molde Casero",
    descripcion: "Pan esponjoso y con corteza dorada, amasado en la Mambo con la Pala MamboMix en modo espiga.",
    imagen: "/images/recipes/pan-de-molde-mambo.jpg",
    categoria: "panes-masas",
    tiempo_total_min: 120,
    comensales: 10,
    dificultad: "Media",
    ingredientes: [
      "500 g de harina de fuerza",
      "10 g de sal",
      "10 g de levadura fresca",
      "30 g de azúcar",
      "30 g de mantequilla",
      "300 ml de leche tibia",
    ],
    pasos_mambo: [
      { paso_numero: 1, instruccion: "Disolver la levadura en la leche tibia. Colocar la harina, la sal y el azúcar en la jarra.", accesorio: "Pala MamboMix", velocidad: 1, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: 1 },
      { paso_numero: 2, instruccion: "Añadir la leche con levadura. Amasar en modo espiga (Pala MamboMix).", accesorio: "Pala MamboMix", velocidad: 2, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: 5 },
      { paso_numero: 3, instruccion: "Incorporar la mantequilla y seguir amasando.", accesorio: "Pala MamboMix", velocidad: 2, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: 5 },
      { paso_numero: 4, instruccion: "Dejar leudar 1 hora. Formar y colocar en molde. Hornear a 180 ºC durante 30 min.", accesorio: "Ninguno", velocidad: 0, temperatura_c: null, potencia_calorifica: null, tiempo_minutos: 90 },
    ],
    creado_en: "2026-08-11",
  },
];
